apiVersion: apps/v1
kind: Deployment
metadata:
  name: poto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poto
  template:
    metadata:
      labels:
        app: poto
    spec:
      containers:
      - image: okteto.dev/poto:latest
        name: poto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "3cd9ed1e-7217-417d-92aa-7afa37f26ec2"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "3cd9ed1e-7217-417d-92aa-7afa37f26ec2"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
