apiVersion: apps/v1
kind: Deployment
metadata:
  name: toto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toto
  template:
    metadata:
      labels:
        app: toto
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: toto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "599061e7-a2da-4c3b-a017-9066c3f87872"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "599061e7-a2da-4c3b-a017-9066c3f87872"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
